# Generated by Django 4.2.16 on 2024-12-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uploadedimage_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
