# Generated by Django 4.2.16 on 2024-12-06 15:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_uploadedimage_author_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
